/**
 * Mapping COMPLET du BILAN selon les formulaires officiels CERFA 2050-SD et 2051-SD
 * Copié depuis backend/src/bilan/bilan-mapping-cerfa.seed.ts
 * Adapté pour PWA avec IndexedDB
 */

export interface BilanMapping {
  section: string;
  ligne_libelle: string;
  code_poste: string;
  code_cerfa: string | null;
  niveau: number;
  ordre_affichage: number;
  compte_debut: string | null;
  compte_fin: string | null;
  comptes_specifiques: string | null;
  actif: boolean;
}

export const BILAN_MAPPINGS: BilanMapping[] = [
  // ========================================
  // BILAN ACTIF (Formulaire 2050-SD)
  // ========================================

  // CAPITAL SOUSCRIT NON APPELÉ
  {
    section: 'ACTIF',
    ligne_libelle: 'CAPITAL SOUSCRIT NON APPELÉ',
    code_poste: 'AA',
    code_cerfa: 'AA',
    niveau: 1,
    ordre_affichage: 10,
    compte_debut: '109',
    compte_fin: '109',
    comptes_specifiques: null,
    actif: true,
  },

  // ACTIF IMMOBILISÉ
  {
    section: 'ACTIF',
    ligne_libelle: 'ACTIF IMMOBILISÉ',
    code_poste: 'ACTIF-IMMO',
    code_cerfa: null,
    niveau: 0,
    ordre_affichage: 20,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: null,
    actif: true,
  },

  // IMMOBILISATIONS INCORPORELLES
  {
    section: 'ACTIF',
    ligne_libelle: 'IMMOBILISATIONS INCORPORELLES',
    code_poste: 'IMMO-INCORP',
    code_cerfa: null,
    niveau: 1,
    ordre_affichage: 30,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Frais d\'établissement',
    code_poste: 'AB',
    code_cerfa: 'AB',
    niveau: 2,
    ordre_affichage: 31,
    compte_debut: '201',
    compte_fin: '201',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Frais d\'établissement (amortissements)',
    code_poste: 'AC',
    code_cerfa: 'AC',
    niveau: 2,
    ordre_affichage: 32,
    compte_debut: '2801',
    compte_fin: '2801',
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Frais de développement',
    code_poste: 'CX',
    code_cerfa: 'CX',
    niveau: 2,
    ordre_affichage: 33,
    compte_debut: '203',
    compte_fin: '203',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Frais de développement (amortissements)',
    code_poste: 'CQ',
    code_cerfa: 'CQ',
    niveau: 2,
    ordre_affichage: 34,
    compte_debut: '2803',
    compte_fin: '2803',
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Concessions, brevets et droits similaires',
    code_poste: 'AF',
    code_cerfa: 'AF',
    niveau: 2,
    ordre_affichage: 35,
    compte_debut: '205',
    compte_fin: '205',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Concessions, brevets (amortissements)',
    code_poste: 'AG',
    code_cerfa: 'AG',
    niveau: 2,
    ordre_affichage: 36,
    compte_debut: '2805',
    compte_fin: '2805',
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Fonds commercial',
    code_poste: 'AH',
    code_cerfa: 'AH',
    niveau: 2,
    ordre_affichage: 37,
    compte_debut: '206',
    compte_fin: '207',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Fonds commercial (amortissements)',
    code_poste: 'AI',
    code_cerfa: 'AI',
    niveau: 2,
    ordre_affichage: 38,
    compte_debut: '2806',
    compte_fin: '2807',
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Autres immobilisations incorporelles',
    code_poste: 'AJ',
    code_cerfa: 'AJ',
    niveau: 2,
    ordre_affichage: 39,
    compte_debut: '208',
    compte_fin: '208',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Autres immobilisations incorporelles (amortissements)',
    code_poste: 'AK',
    code_cerfa: 'AK',
    niveau: 2,
    ordre_affichage: 40,
    compte_debut: '2808',
    compte_fin: '2808',
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Avances et acomptes sur immobilisations incorporelles',
    code_poste: 'AL',
    code_cerfa: 'AL',
    niveau: 2,
    ordre_affichage: 41,
    compte_debut: '237',
    compte_fin: '237',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Avances et acomptes (amortissements)',
    code_poste: 'AM',
    code_cerfa: 'AM',
    niveau: 2,
    ordre_affichage: 42,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },

  // IMMOBILISATIONS CORPORELLES
  {
    section: 'ACTIF',
    ligne_libelle: 'IMMOBILISATIONS CORPORELLES',
    code_poste: 'IMMO-CORP',
    code_cerfa: null,
    niveau: 1,
    ordre_affichage: 50,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Terrains',
    code_poste: 'AN',
    code_cerfa: 'AN',
    niveau: 2,
    ordre_affichage: 51,
    compte_debut: '211',
    compte_fin: '211',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Terrains (amortissements)',
    code_poste: 'AO',
    code_cerfa: 'AO',
    niveau: 2,
    ordre_affichage: 52,
    compte_debut: '2811',
    compte_fin: '2811',
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Constructions',
    code_poste: 'AP',
    code_cerfa: 'AP',
    niveau: 2,
    ordre_affichage: 53,
    compte_debut: '213',
    compte_fin: '213',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Constructions (amortissements)',
    code_poste: 'AQ',
    code_cerfa: 'AQ',
    niveau: 2,
    ordre_affichage: 54,
    compte_debut: '2813',
    compte_fin: '2813',
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Installations techniques, matériel et outillage industriels',
    code_poste: 'AR',
    code_cerfa: 'AR',
    niveau: 2,
    ordre_affichage: 55,
    compte_debut: '215',
    compte_fin: '215',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Installations techniques (amortissements)',
    code_poste: 'AS',
    code_cerfa: 'AS',
    niveau: 2,
    ordre_affichage: 56,
    compte_debut: '2815',
    compte_fin: '2815',
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Autres immobilisations corporelles',
    code_poste: 'AT',
    code_cerfa: 'AT',
    niveau: 2,
    ordre_affichage: 57,
    compte_debut: '218',
    compte_fin: '218',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Autres immobilisations corporelles (amortissements)',
    code_poste: 'AU',
    code_cerfa: 'AU',
    niveau: 2,
    ordre_affichage: 58,
    compte_debut: '2818',
    compte_fin: '2818',
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Immobilisations en cours',
    code_poste: 'AV',
    code_cerfa: 'AV',
    niveau: 2,
    ordre_affichage: 59,
    compte_debut: '23',
    compte_fin: '23',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Immobilisations en cours (amortissements)',
    code_poste: 'AW',
    code_cerfa: 'AW',
    niveau: 2,
    ordre_affichage: 60,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Avances et acomptes',
    code_poste: 'AX',
    code_cerfa: 'AX',
    niveau: 2,
    ordre_affichage: 61,
    compte_debut: '238',
    compte_fin: '238',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Avances et acomptes (amortissements)',
    code_poste: 'AY',
    code_cerfa: 'AY',
    niveau: 2,
    ordre_affichage: 62,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },

  // IMMOBILISATIONS FINANCIÈRES
  {
    section: 'ACTIF',
    ligne_libelle: 'IMMOBILISATIONS FINANCIÈRES',
    code_poste: 'IMMO-FIN',
    code_cerfa: null,
    niveau: 1,
    ordre_affichage: 70,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Participations évaluées selon la méthode de mise en équivalence',
    code_poste: 'CS',
    code_cerfa: 'CS',
    niveau: 2,
    ordre_affichage: 71,
    compte_debut: '261',
    compte_fin: '261',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Participations évaluées (provisions)',
    code_poste: 'CT',
    code_cerfa: 'CT',
    niveau: 2,
    ordre_affichage: 72,
    compte_debut: '2961',
    compte_fin: '2961',
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Autres participations',
    code_poste: 'CU',
    code_cerfa: 'CU',
    niveau: 2,
    ordre_affichage: 73,
    compte_debut: '261',
    compte_fin: '261',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Autres participations (provisions)',
    code_poste: 'CV',
    code_cerfa: 'CV',
    niveau: 2,
    ordre_affichage: 74,
    compte_debut: '2961',
    compte_fin: '2961',
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Créances rattachées à des participations',
    code_poste: 'BB',
    code_cerfa: 'BB',
    niveau: 2,
    ordre_affichage: 75,
    compte_debut: '266',
    compte_fin: '267',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Créances rattachées (provisions)',
    code_poste: 'BC',
    code_cerfa: 'BC',
    niveau: 2,
    ordre_affichage: 76,
    compte_debut: '2966',
    compte_fin: '2967',
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Autres titres immobilisés',
    code_poste: 'BD',
    code_cerfa: 'BD',
    niveau: 2,
    ordre_affichage: 77,
    compte_debut: '271',
    compte_fin: '272',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Autres titres immobilisés (provisions)',
    code_poste: 'BE',
    code_cerfa: 'BE',
    niveau: 2,
    ordre_affichage: 78,
    compte_debut: '2971',
    compte_fin: '2972',
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Prêts',
    code_poste: 'BF',
    code_cerfa: 'BF',
    niveau: 2,
    ordre_affichage: 79,
    compte_debut: '274',
    compte_fin: '274',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Prêts (provisions)',
    code_poste: 'BG',
    code_cerfa: 'BG',
    niveau: 2,
    ordre_affichage: 80,
    compte_debut: '2974',
    compte_fin: '2974',
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Autres immobilisations financières',
    code_poste: 'BH',
    code_cerfa: 'BH',
    niveau: 2,
    ordre_affichage: 81,
    compte_debut: '275',
    compte_fin: '279',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Autres immobilisations financières (provisions)',
    code_poste: 'BI',
    code_cerfa: 'BI',
    niveau: 2,
    ordre_affichage: 82,
    compte_debut: '2975',
    compte_fin: '2979',
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'TOTAL (II) IMMOBILISATIONS',
    code_poste: 'BJ',
    code_cerfa: 'BJ',
    niveau: 1,
    ordre_affichage: 90,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: '{"type":"somme_lignes","codes":["AB","CX","AF","AH","AJ","AL","AN","AP","AR","AT","AV","AX","CS","CU","BB","BD","BF","BH"]}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'TOTAL (II) AMORTISSEMENTS',
    code_poste: 'BK',
    code_cerfa: 'BK',
    niveau: 1,
    ordre_affichage: 91,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: '{"type":"somme_lignes","codes":["AC","CQ","AG","AI","AK","AM","AO","AQ","AS","AU","AW","AY"],"inverser_signe":true}',
    actif: true,
  },

  // ACTIF CIRCULANT
  {
    section: 'ACTIF',
    ligne_libelle: 'ACTIF CIRCULANT',
    code_poste: 'ACTIF-CIRC',
    code_cerfa: null,
    niveau: 0,
    ordre_affichage: 100,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: null,
    actif: true,
  },

  // STOCKS
  {
    section: 'ACTIF',
    ligne_libelle: 'STOCKS',
    code_poste: 'STOCKS',
    code_cerfa: null,
    niveau: 1,
    ordre_affichage: 110,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Matières premières, approvisionnements',
    code_poste: 'BL',
    code_cerfa: 'BL',
    niveau: 2,
    ordre_affichage: 111,
    compte_debut: '31',
    compte_fin: '32',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Matières premières (provisions)',
    code_poste: 'BM',
    code_cerfa: 'BM',
    niveau: 2,
    ordre_affichage: 112,
    compte_debut: '391',
    compte_fin: '392',
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'En cours de production de biens',
    code_poste: 'BN',
    code_cerfa: 'BN',
    niveau: 2,
    ordre_affichage: 113,
    compte_debut: '33',
    compte_fin: '33',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'En cours de production de biens (provisions)',
    code_poste: 'BO',
    code_cerfa: 'BO',
    niveau: 2,
    ordre_affichage: 114,
    compte_debut: '393',
    compte_fin: '393',
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'En cours de production de services',
    code_poste: 'BP',
    code_cerfa: 'BP',
    niveau: 2,
    ordre_affichage: 115,
    compte_debut: '34',
    compte_fin: '34',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'En cours de production de services (provisions)',
    code_poste: 'BQ',
    code_cerfa: 'BQ',
    niveau: 2,
    ordre_affichage: 116,
    compte_debut: '394',
    compte_fin: '394',
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Produits intermédiaires et finis',
    code_poste: 'BR',
    code_cerfa: 'BR',
    niveau: 2,
    ordre_affichage: 117,
    compte_debut: '35',
    compte_fin: '35',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Produits intermédiaires et finis (provisions)',
    code_poste: 'BS',
    code_cerfa: 'BS',
    niveau: 2,
    ordre_affichage: 118,
    compte_debut: '395',
    compte_fin: '395',
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Marchandises',
    code_poste: 'BT',
    code_cerfa: 'BT',
    niveau: 2,
    ordre_affichage: 119,
    compte_debut: '37',
    compte_fin: '37',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Marchandises (provisions)',
    code_poste: 'BU',
    code_cerfa: 'BU',
    niveau: 2,
    ordre_affichage: 120,
    compte_debut: '397',
    compte_fin: '397',
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },

  // CRÉANCES
  {
    section: 'ACTIF',
    ligne_libelle: 'CRÉANCES',
    code_poste: 'CREANCES',
    code_cerfa: null,
    niveau: 1,
    ordre_affichage: 130,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Avances et acomptes versés sur commandes',
    code_poste: 'BV',
    code_cerfa: 'BV',
    niveau: 2,
    ordre_affichage: 131,
    compte_debut: '4091',
    compte_fin: '4091',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Avances et acomptes versés (provisions)',
    code_poste: 'BW',
    code_cerfa: 'BW',
    niveau: 2,
    ordre_affichage: 132,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Clients et comptes rattachés',
    code_poste: 'BX',
    code_cerfa: 'BX',
    niveau: 2,
    ordre_affichage: 133,
    compte_debut: '41',
    compte_fin: '41',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Clients et comptes rattachés (provisions)',
    code_poste: 'BY',
    code_cerfa: 'BY',
    niveau: 2,
    ordre_affichage: 134,
    compte_debut: '491',
    compte_fin: '491',
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Autres créances',
    code_poste: 'BZ',
    code_cerfa: 'BZ',
    niveau: 2,
    ordre_affichage: 135,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: '["40","42","43","44","45","46","47","480","481","482","483","484","485","488","489"]',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Autres créances (provisions)',
    code_poste: 'CA',
    code_cerfa: 'CA',
    niveau: 2,
    ordre_affichage: 136,
    compte_debut: '492',
    compte_fin: '498',
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Capital souscrit et appelé, non versé',
    code_poste: 'CB',
    code_cerfa: 'CB',
    niveau: 2,
    ordre_affichage: 137,
    compte_debut: '4562',
    compte_fin: '4562',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Capital souscrit et appelé (provisions)',
    code_poste: 'CC',
    code_cerfa: 'CC',
    niveau: 2,
    ordre_affichage: 138,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },

  // DIVERS
  {
    section: 'ACTIF',
    ligne_libelle: 'DIVERS',
    code_poste: 'DIVERS',
    code_cerfa: null,
    niveau: 1,
    ordre_affichage: 140,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Valeurs mobilières de placement',
    code_poste: 'CD',
    code_cerfa: 'CD',
    niveau: 2,
    ordre_affichage: 141,
    compte_debut: '50',
    compte_fin: '50',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Valeurs mobilières de placement (provisions)',
    code_poste: 'CE',
    code_cerfa: 'CE',
    niveau: 2,
    ordre_affichage: 142,
    compte_debut: '590',
    compte_fin: '590',
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Disponibilités',
    code_poste: 'CF',
    code_cerfa: 'CF',
    niveau: 2,
    ordre_affichage: 143,
    compte_debut: '51',
    compte_fin: '53',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Disponibilités (provisions)',
    code_poste: 'CG',
    code_cerfa: 'CG',
    niveau: 2,
    ordre_affichage: 144,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Charges constatées d\'avance',
    code_poste: 'CH',
    code_cerfa: 'CH',
    niveau: 2,
    ordre_affichage: 145,
    compte_debut: '486',
    compte_fin: '486',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Charges constatées d\'avance (provisions)',
    code_poste: 'CI',
    code_cerfa: 'CI',
    niveau: 2,
    ordre_affichage: 146,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: '{"inverser_signe": true}',
    actif: true,
  },

  // TOTAUX ACTIF CIRCULANT
  {
    section: 'ACTIF',
    ligne_libelle: 'TOTAL ACTIF CIRCULANT (III)',
    code_poste: 'CJ',
    code_cerfa: 'CJ',
    niveau: 1,
    ordre_affichage: 150,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: '{"type":"somme_lignes","codes":["BL","BN","BP","BR","BT","BV","BX","BZ","CB","CD","CF","CH"]}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'TOTAL ACTIF CIRCULANT (provisions)',
    code_poste: 'CK',
    code_cerfa: 'CK',
    niveau: 1,
    ordre_affichage: 151,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: '{"type":"somme_lignes","codes":["BM","BO","BQ","BS","BU","BW","BY","CA","CC","CE","CG","CI"],"inverser_signe":true}',
    actif: true,
  },

  // COMPTES DE RÉGULARISATION
  {
    section: 'ACTIF',
    ligne_libelle: 'Frais d\'émission d\'emprunt à étaler (IV)',
    code_poste: 'CW',
    code_cerfa: 'CW',
    niveau: 1,
    ordre_affichage: 160,
    compte_debut: '4816',
    compte_fin: '4816',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Primes de remboursement des obligations (V)',
    code_poste: 'CM',
    code_cerfa: 'CM',
    niveau: 1,
    ordre_affichage: 161,
    compte_debut: '169',
    compte_fin: '169',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'Écarts de conversion actif (VI)',
    code_poste: 'CN',
    code_cerfa: 'CN',
    niveau: 1,
    ordre_affichage: 162,
    compte_debut: '476',
    compte_fin: '476',
    comptes_specifiques: null,
    actif: true,
  },

  // TOTAL GÉNÉRAL ACTIF
  {
    section: 'ACTIF',
    ligne_libelle: 'TOTAL GÉNÉRAL ACTIF (I à VI)',
    code_poste: 'CO',
    code_cerfa: 'CO',
    niveau: 0,
    ordre_affichage: 200,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: '{"type":"somme_lignes","codes":["AA","BJ","CJ","CW","CM","CN"]}',
    actif: true,
  },
  {
    section: 'ACTIF',
    ligne_libelle: 'TOTAL GÉNÉRAL ACTIF (après déduction des amortissements)',
    code_poste: '1A',
    code_cerfa: '1A',
    niveau: 0,
    ordre_affichage: 201,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: '{"type":"difference_lignes","base":"CO","soustrait":"BK"}',
    actif: true,
  },

  // ========================================
  // BILAN PASSIF (Formulaire 2051-SD)
  // ========================================

  // CAPITAUX PROPRES
  {
    section: 'PASSIF',
    ligne_libelle: 'CAPITAUX PROPRES',
    code_poste: 'CAP-PROPRES',
    code_cerfa: null,
    niveau: 0,
    ordre_affichage: 300,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Capital social ou individuel',
    code_poste: 'DA',
    code_cerfa: 'DA',
    niveau: 1,
    ordre_affichage: 301,
    compte_debut: '101',
    compte_fin: '101',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Primes d\'émission, de fusion, d\'apport',
    code_poste: 'DB',
    code_cerfa: 'DB',
    niveau: 1,
    ordre_affichage: 302,
    compte_debut: '104',
    compte_fin: '104',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Écarts de réévaluation',
    code_poste: 'DC',
    code_cerfa: 'DC',
    niveau: 1,
    ordre_affichage: 303,
    compte_debut: '105',
    compte_fin: '105',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Réserve légale',
    code_poste: 'DD',
    code_cerfa: 'DD',
    niveau: 1,
    ordre_affichage: 304,
    compte_debut: '1061',
    compte_fin: '1061',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Réserves statutaires ou contractuelles',
    code_poste: 'DE',
    code_cerfa: 'DE',
    niveau: 1,
    ordre_affichage: 305,
    compte_debut: '1064',
    compte_fin: '1064',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Réserves réglementées',
    code_poste: 'DF',
    code_cerfa: 'DF',
    niveau: 1,
    ordre_affichage: 306,
    compte_debut: '1062',
    compte_fin: '1063',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Autres réserves',
    code_poste: 'DG',
    code_cerfa: 'DG',
    niveau: 1,
    ordre_affichage: 307,
    compte_debut: '1068',
    compte_fin: '1068',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Report à nouveau',
    code_poste: 'DH',
    code_cerfa: 'DH',
    niveau: 1,
    ordre_affichage: 308,
    compte_debut: '11',
    compte_fin: '11',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'RÉSULTAT DE L\'EXERCICE (bénéfice ou perte)',
    code_poste: 'DI',
    code_cerfa: 'DI',
    niveau: 1,
    ordre_affichage: 309,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: '{"type":"resultat_exercice"}',
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Subventions d\'investissement',
    code_poste: 'DJ',
    code_cerfa: 'DJ',
    niveau: 1,
    ordre_affichage: 310,
    compte_debut: '13',
    compte_fin: '13',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Provisions réglementées',
    code_poste: 'DK',
    code_cerfa: 'DK',
    niveau: 1,
    ordre_affichage: 311,
    compte_debut: '14',
    compte_fin: '14',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'TOTAL CAPITAUX PROPRES (I)',
    code_poste: 'DL',
    code_cerfa: 'DL',
    niveau: 0,
    ordre_affichage: 320,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: '{"type":"somme_lignes","codes":["DA","DB","DC","DD","DE","DF","DG","DH","DI","DJ","DK"]}',
    actif: true,
  },

  // AUTRES FONDS PROPRES
  {
    section: 'PASSIF',
    ligne_libelle: 'Autres fonds propres',
    code_poste: 'AUTRES-FONDS',
    code_cerfa: null,
    niveau: 0,
    ordre_affichage: 330,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Produit des émissions de titres participatifs',
    code_poste: 'DM',
    code_cerfa: 'DM',
    niveau: 1,
    ordre_affichage: 331,
    compte_debut: '162',
    compte_fin: '162',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Avances conditionnées',
    code_poste: 'DN',
    code_cerfa: 'DN',
    niveau: 1,
    ordre_affichage: 332,
    compte_debut: '166',
    compte_fin: '166',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'TOTAL AUTRES FONDS PROPRES (II)',
    code_poste: 'DO',
    code_cerfa: 'DO',
    niveau: 0,
    ordre_affichage: 340,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: '{"type":"somme_lignes","codes":["DM","DN"]}',
    actif: true,
  },

  // PROVISIONS POUR RISQUES ET CHARGES
  {
    section: 'PASSIF',
    ligne_libelle: 'Provisions pour risques et charges',
    code_poste: 'PROVISIONS',
    code_cerfa: null,
    niveau: 0,
    ordre_affichage: 350,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Provisions pour risques',
    code_poste: 'DP',
    code_cerfa: 'DP',
    niveau: 1,
    ordre_affichage: 351,
    compte_debut: '151',
    compte_fin: '157',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Provisions pour charges',
    code_poste: 'DQ',
    code_cerfa: 'DQ',
    niveau: 1,
    ordre_affichage: 352,
    compte_debut: '158',
    compte_fin: '158',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'TOTAL PROVISIONS (III)',
    code_poste: 'DR',
    code_cerfa: 'DR',
    niveau: 0,
    ordre_affichage: 360,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: '{"type":"somme_lignes","codes":["DP","DQ"]}',
    actif: true,
  },

  // DETTES
  {
    section: 'PASSIF',
    ligne_libelle: 'DETTES',
    code_poste: 'DETTES',
    code_cerfa: null,
    niveau: 0,
    ordre_affichage: 370,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Emprunts obligataires convertibles',
    code_poste: 'DS',
    code_cerfa: 'DS',
    niveau: 1,
    ordre_affichage: 371,
    compte_debut: '161',
    compte_fin: '161',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Autres emprunts obligataires',
    code_poste: 'DT',
    code_cerfa: 'DT',
    niveau: 1,
    ordre_affichage: 372,
    compte_debut: '163',
    compte_fin: '163',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Emprunts et dettes auprès des établissements de crédit',
    code_poste: 'DU',
    code_cerfa: 'DU',
    niveau: 1,
    ordre_affichage: 373,
    compte_debut: '164',
    compte_fin: '164',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Emprunts et dettes financières divers',
    code_poste: 'DV',
    code_cerfa: 'DV',
    niveau: 1,
    ordre_affichage: 374,
    compte_debut: '165',
    compte_fin: '168',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Avances et acomptes reçus sur commandes en cours',
    code_poste: 'DW',
    code_cerfa: 'DW',
    niveau: 1,
    ordre_affichage: 375,
    compte_debut: '4191',
    compte_fin: '4191',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Dettes fournisseurs et comptes rattachés',
    code_poste: 'DX',
    code_cerfa: 'DX',
    niveau: 1,
    ordre_affichage: 376,
    compte_debut: '40',
    compte_fin: '40',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Dettes fiscales et sociales',
    code_poste: 'DY',
    code_cerfa: 'DY',
    niveau: 1,
    ordre_affichage: 377,
    compte_debut: '43',
    compte_fin: '44',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Dettes sur immobilisations et comptes rattachés',
    code_poste: 'DZ',
    code_cerfa: 'DZ',
    niveau: 1,
    ordre_affichage: 378,
    compte_debut: '404',
    compte_fin: '405',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Autres dettes',
    code_poste: 'EA',
    code_cerfa: 'EA',
    niveau: 1,
    ordre_affichage: 379,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: '["41","42","45","46","47","480","481","482","483","484","485","486","488","489"]',
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Produits constatés d\'avance',
    code_poste: 'EB',
    code_cerfa: 'EB',
    niveau: 1,
    ordre_affichage: 380,
    compte_debut: '487',
    compte_fin: '487',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'TOTAL DETTES (IV)',
    code_poste: 'EC',
    code_cerfa: 'EC',
    niveau: 0,
    ordre_affichage: 390,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: '{"type":"somme_lignes","codes":["DS","DT","DU","DV","DW","DX","DY","DZ","EA","EB"]}',
    actif: true,
  },

  // COMPTES DE RÉGULARISATION PASSIF
  {
    section: 'PASSIF',
    ligne_libelle: 'Écart de conversion passif (V)',
    code_poste: 'ED',
    code_cerfa: 'ED',
    niveau: 0,
    ordre_affichage: 400,
    compte_debut: '477',
    compte_fin: '477',
    comptes_specifiques: null,
    actif: true,
  },

  // TOTAL GÉNÉRAL PASSIF
  {
    section: 'PASSIF',
    ligne_libelle: 'TOTAL GÉNÉRAL PASSIF (I à V)',
    code_poste: 'EE',
    code_cerfa: 'EE',
    niveau: 0,
    ordre_affichage: 500,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: '{"type":"somme_lignes","codes":["DL","DO","DR","EC","ED"]}',
    actif: true,
  },

  // RENVOIS PASSIF (codes EF, EG, EH, EI, EJ, EK)
  {
    section: 'PASSIF',
    ligne_libelle: 'Dont réserve spéciale des plus-values à long terme',
    code_poste: 'EF',
    code_cerfa: 'EF',
    niveau: 2,
    ordre_affichage: 501,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Dettes et produits constatés d\'avance à moins d\'un an',
    code_poste: 'EG',
    code_cerfa: 'EG',
    niveau: 2,
    ordre_affichage: 502,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Dont concours bancaires courants, et soldes créditeurs de banques',
    code_poste: 'EH',
    code_cerfa: 'EH',
    niveau: 2,
    ordre_affichage: 503,
    compte_debut: '519',
    compte_fin: '519',
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Dont emprunts participatifs',
    code_poste: 'EI',
    code_cerfa: 'EI',
    niveau: 2,
    ordre_affichage: 504,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Dont réserve relative à l\'achat d\'œuvres originales d\'artistes vivants',
    code_poste: 'EJ',
    code_cerfa: 'EJ',
    niveau: 2,
    ordre_affichage: 505,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: null,
    actif: true,
  },
  {
    section: 'PASSIF',
    ligne_libelle: 'Dont écart d\'équivalence',
    code_poste: 'EK',
    code_cerfa: 'EK',
    niveau: 2,
    ordre_affichage: 506,
    compte_debut: null,
    compte_fin: null,
    comptes_specifiques: null,
    actif: true,
  },
];
