/**
 * Mappings du Compte de Résultat selon CERFA 2052-SD et 2053-SD
 * Copié depuis backend/src/compte-resultat/init-compte-resultat-mapping.ts
 */

export interface CompteResultatMapping {
  section: string;
  categorie: string;
  ligne_libelle: string;
  compte_debut?: string;
  compte_fin?: string;
  comptes_specifiques?: string;
  niveau: number;
  ordre_affichage: number;
  code_poste: string;
  code_cerfa?: string;
  actif: boolean;
}

export const COMPTE_RESULTAT_MAPPINGS: CompteResultatMapping[] = [
  // ============================
  // PRODUITS D'EXPLOITATION
  // ============================
  {
    section: 'PRODUITS',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'PRODUITS D\'EXPLOITATION',
    niveau: 1,
    ordre_affichage: 10,
    code_poste: 'PROD_EXPLOITATION_TITRE',
    actif: true,
  },
  {
    section: 'PRODUITS',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'Ventes de marchandises',
    compte_debut: '707',
    compte_fin: '707',
    niveau: 3,
    ordre_affichage: 20,
    code_poste: 'FA',
    code_cerfa: 'FA',
    actif: true,
  },
  {
    section: 'PRODUITS',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'Production vendue - Biens',
    compte_debut: '701',
    compte_fin: '705',
    niveau: 3,
    ordre_affichage: 30,
    code_poste: 'FD',
    code_cerfa: 'FD',
    actif: true,
  },
  {
    section: 'PRODUITS',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'Production vendue - Services',
    compte_debut: '706',
    compte_fin: '706',
    niveau: 3,
    ordre_affichage: 40,
    code_poste: 'FG',
    code_cerfa: 'FG',
    actif: true,
  },
  {
    section: 'PRODUITS',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'Chiffres d\'affaires nets',
    comptes_specifiques: JSON.stringify({
      type: 'somme_lignes',
      codes: ['FA', 'FD', 'FG'],
    }),
    niveau: 2,
    ordre_affichage: 50,
    code_poste: 'FL',
    code_cerfa: 'FL',
    actif: true,
  },
  {
    section: 'PRODUITS',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'Production stockée',
    compte_debut: '713',
    compte_fin: '713',
    niveau: 3,
    ordre_affichage: 60,
    code_poste: 'FM',
    code_cerfa: 'FM',
    actif: true,
  },
  {
    section: 'PRODUITS',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'Production immobilisée',
    compte_debut: '72',
    compte_fin: '72',
    niveau: 3,
    ordre_affichage: 70,
    code_poste: 'FN',
    code_cerfa: 'FN',
    actif: true,
  },
  {
    section: 'PRODUITS',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'Subventions d\'exploitation',
    compte_debut: '74',
    compte_fin: '74',
    niveau: 3,
    ordre_affichage: 80,
    code_poste: 'FO',
    code_cerfa: 'FO',
    actif: true,
  },
  {
    section: 'PRODUITS',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'Reprises sur amortissements et provisions, transferts de charges',
    comptes_specifiques: JSON.stringify(['781', '791']),
    niveau: 3,
    ordre_affichage: 90,
    code_poste: 'FP',
    code_cerfa: 'FP',
    actif: true,
  },
  {
    section: 'PRODUITS',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'Autres produits',
    compte_debut: '75',
    compte_fin: '75',
    niveau: 3,
    ordre_affichage: 100,
    code_poste: 'FQ',
    code_cerfa: 'FQ',
    actif: true,
  },
  {
    section: 'PRODUITS',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'TOTAL DES PRODUITS D\'EXPLOITATION (I)',
    comptes_specifiques: JSON.stringify({
      type: 'somme_lignes',
      codes: ['FL', 'FM', 'FN', 'FO', 'FP', 'FQ'],
    }),
    niveau: 2,
    ordre_affichage: 110,
    code_poste: 'FR',
    code_cerfa: 'FR',
    actif: true,
  },

  // ============================
  // CHARGES D'EXPLOITATION
  // ============================
  {
    section: 'CHARGES',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'CHARGES D\'EXPLOITATION',
    niveau: 1,
    ordre_affichage: 120,
    code_poste: 'CHARGES_EXPLOITATION_TITRE',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'Achats de marchandises (y compris droits de douane)',
    compte_debut: '607',
    compte_fin: '607',
    niveau: 3,
    ordre_affichage: 130,
    code_poste: 'FS',
    code_cerfa: 'FS',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'Variation de stocks (marchandises)',
    compte_debut: '6037',
    compte_fin: '6037',
    niveau: 3,
    ordre_affichage: 140,
    code_poste: 'FT',
    code_cerfa: 'FT',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'Achats de matières premières et autres approvisionnements',
    comptes_specifiques: JSON.stringify(['601', '602', '604', '605', '606', '608']),
    niveau: 3,
    ordre_affichage: 150,
    code_poste: 'FU',
    code_cerfa: 'FU',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'Variation de stocks (matières premières et approvisionnements)',
    comptes_specifiques: JSON.stringify(['6031', '6032', '6035']),
    niveau: 3,
    ordre_affichage: 160,
    code_poste: 'FV',
    code_cerfa: 'FV',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'Autres achats et charges externes',
    compte_debut: '61',
    compte_fin: '62',
    niveau: 3,
    ordre_affichage: 170,
    code_poste: 'FW',
    code_cerfa: 'FW',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'Impôts, taxes et versements assimilés',
    compte_debut: '63',
    compte_fin: '63',
    niveau: 3,
    ordre_affichage: 180,
    code_poste: 'FX',
    code_cerfa: 'FX',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'Salaires et traitements',
    compte_debut: '641',
    compte_fin: '641',
    niveau: 3,
    ordre_affichage: 190,
    code_poste: 'FY',
    code_cerfa: 'FY',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'Charges sociales',
    compte_debut: '645',
    compte_fin: '648',
    niveau: 3,
    ordre_affichage: 200,
    code_poste: 'FZ',
    code_cerfa: 'FZ',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'Dotations aux amortissements sur immobilisations',
    compte_debut: '6811',
    compte_fin: '6812',
    niveau: 3,
    ordre_affichage: 210,
    code_poste: 'GA',
    code_cerfa: 'GA',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'Dotations aux provisions sur immobilisations',
    compte_debut: '6816',
    compte_fin: '6817',
    niveau: 3,
    ordre_affichage: 220,
    code_poste: 'GB',
    code_cerfa: 'GB',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'Dotations aux provisions sur actif circulant',
    compte_debut: '6817',
    compte_fin: '6817',
    niveau: 3,
    ordre_affichage: 230,
    code_poste: 'GC',
    code_cerfa: 'GC',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'Dotations aux provisions pour risques et charges',
    compte_debut: '6815',
    compte_fin: '6815',
    niveau: 3,
    ordre_affichage: 240,
    code_poste: 'GD',
    code_cerfa: 'GD',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'Autres charges',
    compte_debut: '65',
    compte_fin: '65',
    niveau: 3,
    ordre_affichage: 250,
    code_poste: 'GE',
    code_cerfa: 'GE',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'EXPLOITATION',
    ligne_libelle: 'TOTAL DES CHARGES D\'EXPLOITATION (II)',
    comptes_specifiques: JSON.stringify({
      type: 'somme_lignes',
      codes: ['FS', 'FT', 'FU', 'FV', 'FW', 'FX', 'FY', 'FZ', 'GA', 'GB', 'GC', 'GD', 'GE'],
    }),
    niveau: 2,
    ordre_affichage: 260,
    code_poste: 'GF',
    code_cerfa: 'GF',
    actif: true,
  },
  {
    section: 'RESULTAT',
    categorie: 'EXPLOITATION',
    ligne_libelle: '1 – RÉSULTAT D\'EXPLOITATION (I – II)',
    comptes_specifiques: JSON.stringify({
      type: 'difference_lignes',
      base: 'FR',
      soustrait: 'GF',
    }),
    niveau: 2,
    ordre_affichage: 270,
    code_poste: 'GG',
    code_cerfa: 'GG',
    actif: true,
  },

  // ============================
  // PRODUITS FINANCIERS
  // ============================
  {
    section: 'PRODUITS',
    categorie: 'FINANCIER',
    ligne_libelle: 'PRODUITS FINANCIERS',
    niveau: 1,
    ordre_affichage: 280,
    code_poste: 'PROD_FINANCIERS_TITRE',
    actif: true,
  },
  {
    section: 'PRODUITS',
    categorie: 'FINANCIER',
    ligne_libelle: 'Produits financiers de participations',
    compte_debut: '761',
    compte_fin: '761',
    niveau: 3,
    ordre_affichage: 290,
    code_poste: 'GJ',
    code_cerfa: 'GJ',
    actif: true,
  },
  {
    section: 'PRODUITS',
    categorie: 'FINANCIER',
    ligne_libelle: 'Produits des autres valeurs mobilières et créances de l\'actif immobilisé',
    compte_debut: '762',
    compte_fin: '764',
    niveau: 3,
    ordre_affichage: 300,
    code_poste: 'GK',
    code_cerfa: 'GK',
    actif: true,
  },
  {
    section: 'PRODUITS',
    categorie: 'FINANCIER',
    ligne_libelle: 'Autres intérêts et produits assimilés',
    compte_debut: '765',
    compte_fin: '768',
    niveau: 3,
    ordre_affichage: 310,
    code_poste: 'GL',
    code_cerfa: 'GL',
    actif: true,
  },
  {
    section: 'PRODUITS',
    categorie: 'FINANCIER',
    ligne_libelle: 'Reprises sur provisions et transferts de charges',
    compte_debut: '786',
    compte_fin: '796',
    niveau: 3,
    ordre_affichage: 320,
    code_poste: 'GM',
    code_cerfa: 'GM',
    actif: true,
  },
  {
    section: 'PRODUITS',
    categorie: 'FINANCIER',
    ligne_libelle: 'Différences positives de change',
    compte_debut: '766',
    compte_fin: '766',
    niveau: 3,
    ordre_affichage: 330,
    code_poste: 'GN',
    code_cerfa: 'GN',
    actif: true,
  },
  {
    section: 'PRODUITS',
    categorie: 'FINANCIER',
    ligne_libelle: 'Produits nets sur cessions de valeurs mobilières de placement',
    compte_debut: '767',
    compte_fin: '767',
    niveau: 3,
    ordre_affichage: 340,
    code_poste: 'GO',
    code_cerfa: 'GO',
    actif: true,
  },
  {
    section: 'PRODUITS',
    categorie: 'FINANCIER',
    ligne_libelle: 'TOTAL DES PRODUITS FINANCIERS (V)',
    comptes_specifiques: JSON.stringify({
      type: 'somme_lignes',
      codes: ['GJ', 'GK', 'GL', 'GM', 'GN', 'GO'],
    }),
    niveau: 2,
    ordre_affichage: 350,
    code_poste: 'GP',
    code_cerfa: 'GP',
    actif: true,
  },

  // ============================
  // CHARGES FINANCIÈRES
  // ============================
  {
    section: 'CHARGES',
    categorie: 'FINANCIER',
    ligne_libelle: 'CHARGES FINANCIÈRES',
    niveau: 1,
    ordre_affichage: 360,
    code_poste: 'CHARGES_FINANCIERES_TITRE',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'FINANCIER',
    ligne_libelle: 'Dotations financières aux amortissements et provisions',
    compte_debut: '686',
    compte_fin: '686',
    niveau: 3,
    ordre_affichage: 370,
    code_poste: 'GQ',
    code_cerfa: 'GQ',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'FINANCIER',
    ligne_libelle: 'Intérêts et charges assimilées',
    compte_debut: '661',
    compte_fin: '668',
    niveau: 3,
    ordre_affichage: 380,
    code_poste: 'GR',
    code_cerfa: 'GR',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'FINANCIER',
    ligne_libelle: 'Différences négatives de change',
    compte_debut: '666',
    compte_fin: '666',
    niveau: 3,
    ordre_affichage: 390,
    code_poste: 'GS',
    code_cerfa: 'GS',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'FINANCIER',
    ligne_libelle: 'Charges nettes sur cessions de valeurs mobilières de placement',
    compte_debut: '667',
    compte_fin: '667',
    niveau: 3,
    ordre_affichage: 400,
    code_poste: 'GT',
    code_cerfa: 'GT',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'FINANCIER',
    ligne_libelle: 'TOTAL DES CHARGES FINANCIÈRES (VI)',
    comptes_specifiques: JSON.stringify({
      type: 'somme_lignes',
      codes: ['GQ', 'GR', 'GS', 'GT'],
    }),
    niveau: 2,
    ordre_affichage: 410,
    code_poste: 'GU',
    code_cerfa: 'GU',
    actif: true,
  },
  {
    section: 'RESULTAT',
    categorie: 'FINANCIER',
    ligne_libelle: '2 – RÉSULTAT FINANCIER (V – VI)',
    comptes_specifiques: JSON.stringify({
      type: 'difference_lignes',
      base: 'GP',
      soustrait: 'GU',
    }),
    niveau: 2,
    ordre_affichage: 420,
    code_poste: 'GV',
    code_cerfa: 'GV',
    actif: true,
  },
  {
    section: 'RESULTAT',
    categorie: 'FINANCIER',
    ligne_libelle: '3 – RÉSULTAT COURANT AVANT IMPÔTS (I – II + III – IV + V – VI)',
    comptes_specifiques: JSON.stringify({
      type: 'somme_lignes',
      codes: ['GG', 'GV'],
    }),
    niveau: 2,
    ordre_affichage: 430,
    code_poste: 'GW',
    code_cerfa: 'GW',
    actif: true,
  },

  // ============================
  // PRODUITS EXCEPTIONNELS
  // ============================
  {
    section: 'PRODUITS',
    categorie: 'EXCEPTIONNEL',
    ligne_libelle: 'PRODUITS EXCEPTIONNELS',
    niveau: 1,
    ordre_affichage: 440,
    code_poste: 'PROD_EXCEPTIONNELS_TITRE',
    actif: true,
  },
  {
    section: 'PRODUITS',
    categorie: 'EXCEPTIONNEL',
    ligne_libelle: 'Produits exceptionnels sur opérations de gestion',
    compte_debut: '771',
    compte_fin: '771',
    niveau: 3,
    ordre_affichage: 450,
    code_poste: 'HA',
    code_cerfa: 'HA',
    actif: true,
  },
  {
    section: 'PRODUITS',
    categorie: 'EXCEPTIONNEL',
    ligne_libelle: 'Produits exceptionnels sur opérations en capital',
    compte_debut: '775',
    compte_fin: '778',
    niveau: 3,
    ordre_affichage: 460,
    code_poste: 'HB',
    code_cerfa: 'HB',
    actif: true,
  },
  {
    section: 'PRODUITS',
    categorie: 'EXCEPTIONNEL',
    ligne_libelle: 'Reprises sur provisions et transferts de charges',
    compte_debut: '787',
    compte_fin: '797',
    niveau: 3,
    ordre_affichage: 470,
    code_poste: 'HC',
    code_cerfa: 'HC',
    actif: true,
  },
  {
    section: 'PRODUITS',
    categorie: 'EXCEPTIONNEL',
    ligne_libelle: 'Total des produits exceptionnels (VII)',
    comptes_specifiques: JSON.stringify({
      type: 'somme_lignes',
      codes: ['HA', 'HB', 'HC'],
    }),
    niveau: 2,
    ordre_affichage: 480,
    code_poste: 'HD',
    code_cerfa: 'HD',
    actif: true,
  },

  // ============================
  // CHARGES EXCEPTIONNELLES
  // ============================
  {
    section: 'CHARGES',
    categorie: 'EXCEPTIONNEL',
    ligne_libelle: 'CHARGES EXCEPTIONNELLES',
    niveau: 1,
    ordre_affichage: 490,
    code_poste: 'CHARGES_EXCEPTIONNELLES_TITRE',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'EXCEPTIONNEL',
    ligne_libelle: 'Charges exceptionnelles sur opérations de gestion',
    compte_debut: '671',
    compte_fin: '672',
    niveau: 3,
    ordre_affichage: 500,
    code_poste: 'HE',
    code_cerfa: 'HE',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'EXCEPTIONNEL',
    ligne_libelle: 'Charges exceptionnelles sur opérations en capital',
    compte_debut: '675',
    compte_fin: '678',
    niveau: 3,
    ordre_affichage: 510,
    code_poste: 'HF',
    code_cerfa: 'HF',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'EXCEPTIONNEL',
    ligne_libelle: 'Dotations exceptionnelles aux amortissements et provisions',
    compte_debut: '687',
    compte_fin: '687',
    niveau: 3,
    ordre_affichage: 520,
    code_poste: 'HG',
    code_cerfa: 'HG',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'EXCEPTIONNEL',
    ligne_libelle: 'Total des charges exceptionnelles (VIII)',
    comptes_specifiques: JSON.stringify({
      type: 'somme_lignes',
      codes: ['HE', 'HF', 'HG'],
    }),
    niveau: 2,
    ordre_affichage: 530,
    code_poste: 'HH',
    code_cerfa: 'HH',
    actif: true,
  },
  {
    section: 'RESULTAT',
    categorie: 'EXCEPTIONNEL',
    ligne_libelle: '4 – RÉSULTAT EXCEPTIONNEL (VII – VIII)',
    comptes_specifiques: JSON.stringify({
      type: 'difference_lignes',
      base: 'HD',
      soustrait: 'HH',
    }),
    niveau: 2,
    ordre_affichage: 540,
    code_poste: 'HI',
    code_cerfa: 'HI',
    actif: true,
  },

  // ============================
  // IMPÔTS ET RÉSULTAT NET
  // ============================
  {
    section: 'CHARGES',
    categorie: 'IMPOTS',
    ligne_libelle: 'Participation des salariés aux résultats de l\'entreprise (IX)',
    compte_debut: '691',
    compte_fin: '691',
    niveau: 2,
    ordre_affichage: 550,
    code_poste: 'HJ',
    code_cerfa: 'HJ',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'IMPOTS',
    ligne_libelle: 'Impôts sur les bénéfices (X)',
    compte_debut: '695',
    compte_fin: '698',
    niveau: 2,
    ordre_affichage: 560,
    code_poste: 'HK',
    code_cerfa: 'HK',
    actif: true,
  },
  {
    section: 'PRODUITS',
    categorie: 'RESULTAT',
    ligne_libelle: 'TOTAL DES PRODUITS (I + III + V + VII)',
    comptes_specifiques: JSON.stringify({
      type: 'somme_lignes',
      codes: ['FR', 'GP', 'HD'],
    }),
    niveau: 2,
    ordre_affichage: 570,
    code_poste: 'HL',
    code_cerfa: 'HL',
    actif: true,
  },
  {
    section: 'CHARGES',
    categorie: 'RESULTAT',
    ligne_libelle: 'TOTAL DES CHARGES (II + IV + VI + VIII + IX + X)',
    comptes_specifiques: JSON.stringify({
      type: 'somme_lignes',
      codes: ['GF', 'GU', 'HH', 'HJ', 'HK'],
    }),
    niveau: 2,
    ordre_affichage: 580,
    code_poste: 'HM',
    code_cerfa: 'HM',
    actif: true,
  },
  {
    section: 'RESULTAT',
    categorie: 'RESULTAT',
    ligne_libelle: '5 – BÉNÉFICE OU PERTE (Total des produits – Total des charges)',
    comptes_specifiques: JSON.stringify({
      type: 'difference_lignes',
      base: 'HL',
      soustrait: 'HM',
    }),
    niveau: 1,
    ordre_affichage: 590,
    code_poste: 'HN',
    code_cerfa: 'HN',
    actif: true,
  },
];
